### ISSUE TITLE
about CreateCoreWebView2

### ISSUE THREAD

**Issue by lbgitjp** [rgwood/MinimalWebView#4]
Hi, thank you for this project, I learn a lot from it,
but I have a question about below line:
https://github.com/rgwood/MinimalWebView/blob/5de0ac36e1a5f1b5026efa7e90a91f5eb3777aa8/Program.cs#L75

CreateCoreWebView2 is a async void method,
https://github.com/rgwood/MinimalWebView/blob/5de0ac36e1a5f1b5026efa7e90a91f5eb3777aa8/Program.cs#L112

So when you call **CreateCoreWebView2(hwnd)**; it wlll not wait the result, it will run the next line code, 
WebView2 maybe not finished initialization, is this good?

When I change CreateCoreWebView2 as below:
**private static async Task CreateCoreWebView2(HWND hwnd)**

And call it as as below:
**CreateCoreWebView2(hwnd).GetAwaiter().GetResult();**

It does not work, it is blocked.
 
Do you know how to let **CreateCoreWebView2(hwnd).GetAwaiter().GetResult()** work?

Thanks!

**Comment by rgwood** [comment]
Hi, I'm glad you find the project useful! You bring up a good point; I've been meaning to revisit `CreateCoreWebView2()`.

I think your problem is because you are calling `CreateCoreWebView2(hwnd).GetAwaiter().GetResult();` before [the message loop](https://github.com/rgwood/MinimalWebView/blob/5de0ac36e1a5f1b5026efa7e90a91f5eb3777aa8/Program.cs#L79-L83) starts. The message loop processes `async` continuations (the part of an `async` method after `await`), so it needs to be running before you await `CreateCoreWebView2(hwnd)`.

I can think of 2 ways to improve `CreateCoreWebView2()`:

1. Keep using `async void`, add better error handling. One of the main problems with `async void` is uncaught exceptions; we could wrap the whole function in a try/catch and exit the application if an exception is thrown.
2. Change to `async Task`, save the `Task` (`var initTask = CreateCoreWebView2(hwnd);`) and then `await initTask` in the message loop somehow.

**Comment by lbgitjp** [comment]
Thank you very much!

Now, follow your second way, I add a function as below:

```
    private static void WaitTaskFinished(Task task)
    {
        MSG msg;
        while (PInvoke.GetMessage(out msg, new HWND(), 0, 0))
        {
            PInvoke.TranslateMessage(msg);
            PInvoke.DispatchMessage(msg);

            if (task.Status  == TaskStatus.RanToCompletion)
            {
                break;
            }
        }
    }
```

and call CreateCoreWebView2 as below:

`WaitTaskFinished(CreateCoreWebView2(hwnd));`

It works, very interesting!

I always want to find a tiny UI to work with WebView2, let my asp.net core project can run on desktop,
just find MinimalWebView, only so a few line codes can let WebView2 run in it, it is incredible.

Now, after integrated MinimalWebView and Chromium.AspNetCore.Bridge,  just added a few line codes, my asp.net core project works on desktop.

Thank you!

**Comment by rgwood** [comment]
Glad you got it working.

I ended up taking the first approach; I added better error handling in `CreateCoreWebView2()`: https://github.com/rgwood/MinimalWebView/commit/1090a97c22fb33e07c213917f73f1ad6e2d0b23c

**Comment by lbgitjp** [comment]
I just want every line code works as my expect, who will run first, who will run next..., I need it flow in my control.

In my project, I need my project work as below steps:
1. asp.net host is ready to process request.
2. WebView2 finished initialization
3. WebView2 navigate home page.
4. home page finished loaded.
5. WebView2 shows.
6. Main windows shows.

In my project, I don't find CreateCoreWebView2 has any error, it doesn't raise error.

Thanks!

**Comment by lbgitjp** [comment]
After some learning about async, 
Now I know I shouldn't change **CreateCoreWebView2**, 
I shouldn't add ugly WaitTaskFinished function.
I just use TaskCompletionSource and Event to control my code flow, Everything is running very well.

Thanks!
